# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contacts.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from ListView import ListView
from ListModel import ListModel

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(389, 809)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 391, 161))
        self.graphicsView.setStyleSheet("border-image: url(images/8.png);")
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 40, 91, 91))
        self.graphicsView_2.setStyleSheet("border-image: url(images/3.jpg);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(290, 40, 91, 91))
        self.graphicsView_3.setStyleSheet("border-image: url(images/7.png);")
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(110, 40, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 94, 151, 21))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 190, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 190, 131, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(260, 190, 131, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 160, 31, 31))
        self.pushButton_4.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/6.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(30, 160, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        # self.listView = QtWidgets.QListView(Dialog)
        self.listView = ListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(0, 220, 391, 561))
        self.listView.setToolTip("")
        self.listView.setObjectName("listView")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 780, 181, 28))
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/9.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(180, 780, 211, 28))
        self.pushButton_6.setToolTip("")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/10.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        self.listView.doubleClicked['QModelIndex'].connect(Dialog.Chat)
        self.pushButton_6.clicked['bool'].connect(Dialog.AddContacts)
        self.pushButton_5.clicked['bool'].connect(Dialog.SetSomething)
        self.pushButton.clicked['bool'].connect(Dialog.ShowMessage)
        self.pushButton_2.clicked['bool'].connect(Dialog.ShowContacts)
        self.pushButton_3.clicked['bool'].connect(Dialog.ShowGroup)
        self.pushButton_4.clicked['bool'].connect(Dialog.ShowSearchMessage)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "联系人与群预览"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.pushButton.setText(_translate("Dialog", "消息"))
        self.pushButton_2.setText(_translate("Dialog", "联系人"))
        self.pushButton_3.setText(_translate("Dialog", "群"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "搜索"))
        self.pushButton_5.setAccessibleName(_translate("Dialog", "设置"))
        self.pushButton_5.setAccessibleDescription(_translate("Dialog", "设置"))
        self.pushButton_6.setAccessibleName(_translate("Dialog", "添加好友"))
