# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\web\register.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtWidgets import QComboBox

class MyComboBox(QComboBox):
    click = pyqtSignal()

    def __init__(self,parent=None):
        super(MyComboBox,self).__init__(parent)
    
    def showPopup(self):
        # self.clear()
        self.click.emit()
        QComboBox.showPopup(self)

class Ui_Form1(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(385, 606)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 50, 72, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 50, 191, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 104, 72, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(120, 100, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 154, 72, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 150, 121, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 210, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 72, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = MyComboBox(Form)
        # self.comboBox_4 = QtWidgets.QComboBox(Form)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 260, 87, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 310, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 310, 191, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 410, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 410, 161, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 460, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 460, 161, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(11, 360, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Adobe Gothic Std B")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 360, 180, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 530, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 530, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        self.comboBox_3.activated['int'].connect(Form.Add)
        self.comboBox_3.activated['QString'].connect(Form.Add)
        self.comboBox_4.click.connect(Form.refresh)
        self.pushButton.clicked.connect(Form.readmessage)
        self.pushButton_2.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "姓名："))
        self.label_2.setText(_translate("Form", "性别："))
        self.comboBox.setItemText(0, _translate("Form", "男"))
        self.comboBox.setItemText(1, _translate("Form", "女"))
        self.label_3.setText(_translate("Form", "民族："))
        self.comboBox_2.setItemText(0, _translate("Form", "汉族"))
        self.comboBox_2.setItemText(1, _translate("Form", "回族"))
        self.comboBox_2.setItemText(2, _translate("Form", "壮族"))
        self.comboBox_2.setItemText(3, _translate("Form", "满族"))
        self.comboBox_2.setItemText(4, _translate("Form", "苗族"))
        self.comboBox_2.setItemText(5, _translate("Form", "维吾尔族"))
        self.comboBox_2.setItemText(6, _translate("Form", "土家族"))
        self.comboBox_2.setItemText(7, _translate("Form", "彝族"))
        self.comboBox_2.setItemText(8, _translate("Form", "蒙古族"))
        self.comboBox_2.setItemText(9, _translate("Form", "藏族"))
        self.comboBox_2.setItemText(10, _translate("Form", "布依族"))
        self.comboBox_2.setItemText(11, _translate("Form", "侗族"))
        self.comboBox_2.setItemText(12, _translate("Form", "瑶族"))
        self.comboBox_2.setItemText(13, _translate("Form", "朝鲜族"))
        self.comboBox_2.setItemText(14, _translate("Form", "白族"))
        self.comboBox_2.setItemText(15, _translate("Form", "哈尼族"))
        self.comboBox_2.setItemText(16, _translate("Form", "哈萨克族"))
        self.comboBox_2.setItemText(17, _translate("Form", "黎族"))
        self.comboBox_2.setItemText(18, _translate("Form", "傣族"))
        self.comboBox_2.setItemText(19, _translate("Form", "畲族"))
        self.comboBox_2.setItemText(20, _translate("Form", "傈僳族"))
        self.comboBox_2.setItemText(21, _translate("Form", "仡佬族"))
        self.comboBox_2.setItemText(22, _translate("Form", "东乡族"))
        self.comboBox_2.setItemText(23, _translate("Form", "高山族"))
        self.comboBox_2.setItemText(24, _translate("Form", "拉祜族"))
        self.comboBox_2.setItemText(25, _translate("Form", "水族"))
        self.comboBox_2.setItemText(26, _translate("Form", "佤族"))
        self.comboBox_2.setItemText(27, _translate("Form", "纳西族"))
        self.comboBox_2.setItemText(28, _translate("Form", "羌族"))
        self.comboBox_2.setItemText(29, _translate("Form", "土族"))
        self.comboBox_2.setItemText(30, _translate("Form", "仫佬族"))
        self.comboBox_2.setItemText(31, _translate("Form", "锡伯族"))
        self.comboBox_2.setItemText(32, _translate("Form", "柯尔克孜族"))
        self.comboBox_2.setItemText(33, _translate("Form", "达斡尔族"))
        self.comboBox_2.setItemText(34, _translate("Form", "景颇族"))
        self.comboBox_2.setItemText(35, _translate("Form", "毛南族"))
        self.comboBox_2.setItemText(36, _translate("Form", "撒拉族"))
        self.comboBox_2.setItemText(37, _translate("Form", "塔吉克族"))
        self.comboBox_2.setItemText(38, _translate("Form", "阿昌族"))
        self.comboBox_2.setItemText(39, _translate("Form", "普米族"))
        self.comboBox_2.setItemText(40, _translate("Form", "鄂温克族"))
        self.comboBox_2.setItemText(41, _translate("Form", "怒族"))
        self.comboBox_2.setItemText(42, _translate("Form", "京族"))
        self.comboBox_2.setItemText(43, _translate("Form", "基诺族"))
        self.comboBox_2.setItemText(44, _translate("Form", "德昂族"))
        self.comboBox_2.setItemText(45, _translate("Form", "保安族"))
        self.comboBox_2.setItemText(46, _translate("Form", "俄罗斯族"))
        self.comboBox_2.setItemText(47, _translate("Form", "裕固族"))
        self.comboBox_2.setItemText(48, _translate("Form", "乌孜别克族"))
        self.comboBox_2.setItemText(49, _translate("Form", "门巴族"))
        self.comboBox_2.setItemText(50, _translate("Form", "鄂伦春族"))
        self.comboBox_2.setItemText(51, _translate("Form", "独龙族"))
        self.comboBox_2.setItemText(52, _translate("Form", "塔塔尔族"))
        self.comboBox_2.setItemText(53, _translate("Form", "赫哲族"))
        self.comboBox_2.setItemText(54, _translate("Form", "珞巴族"))
        self.comboBox_2.setItemText(55, _translate("Form", "布朗族"))
        self.label_4.setText(_translate("Form", "省："))
        self.comboBox_3.setItemText(0, _translate("Form", "北京"))
        self.comboBox_3.setItemText(1, _translate("Form", "天津"))
        self.comboBox_3.setItemText(2, _translate("Form", "河北"))
        self.comboBox_3.setItemText(3, _translate("Form", "山西"))
        self.comboBox_3.setItemText(4, _translate("Form", "内蒙古"))
        self.comboBox_3.setItemText(5, _translate("Form", "辽宁"))
        self.comboBox_3.setItemText(6, _translate("Form", "吉林"))
        self.comboBox_3.setItemText(7, _translate("Form", "黑龙江"))
        self.comboBox_3.setItemText(8, _translate("Form", "上海"))
        self.comboBox_3.setItemText(9, _translate("Form", "江苏"))
        self.comboBox_3.setItemText(10, _translate("Form", "浙江"))
        self.comboBox_3.setItemText(11, _translate("Form", "安徽"))
        self.comboBox_3.setItemText(12, _translate("Form", "福建"))
        self.comboBox_3.setItemText(13, _translate("Form", "江西"))
        self.comboBox_3.setItemText(14, _translate("Form", "山东"))
        self.comboBox_3.setItemText(15, _translate("Form", "河南"))
        self.comboBox_3.setItemText(16, _translate("Form", "湖北"))
        self.comboBox_3.setItemText(17, _translate("Form", "湖南"))
        self.comboBox_3.setItemText(18, _translate("Form", "广东"))
        self.comboBox_3.setItemText(19, _translate("Form", "广西"))
        self.comboBox_3.setItemText(20, _translate("Form", "海南"))
        self.comboBox_3.setItemText(21, _translate("Form", "重庆"))
        self.comboBox_3.setItemText(22, _translate("Form", "四川"))
        self.comboBox_3.setItemText(23, _translate("Form", "贵州"))
        self.comboBox_3.setItemText(24, _translate("Form", "云南"))
        self.comboBox_3.setItemText(25, _translate("Form", "西藏"))
        self.comboBox_3.setItemText(26, _translate("Form", "陕西"))
        self.comboBox_3.setItemText(27, _translate("Form", "甘肃"))
        self.comboBox_3.setItemText(28, _translate("Form", "青海"))
        self.comboBox_3.setItemText(29, _translate("Form", "宁夏"))
        self.comboBox_3.setItemText(30, _translate("Form", "新疆"))
        self.label_5.setText(_translate("Form", "市/区："))
        self.label_6.setText(_translate("Form", "电话号码："))
        self.label_7.setText(_translate("Form", "登录密码："))
        self.label_8.setText(_translate("Form", "确认密码："))
        self.label_9.setText(_translate("Form", "身份证号："))
        self.pushButton.setText(_translate("Form", "注册"))
        self.pushButton_2.setText(_translate("Form", "返回"))

